---
- name: after bench
  hosts:
    - isucon1
  vars_files:
    - ../vars/vars.yml
  tasks:
    - import_tasks: ../roles/after_bench/alp.yml

- name: after bench for isucon2
  hosts:
    - isucon2
  vars_files:
    - ../vars/vars.yml
  tasks:
    - import_tasks: ../roles/after_bench/slow-query.yml
