---
- name: before bench
  hosts: isucon1
  vars_files:
    - ../vars/vars.yml
  tasks:
    - import_tasks: ../roles/before_bench/git.yml
    - import_tasks: ../roles/before_bench/app.yml
      become: true
    - import_tasks: ../roles/before_bench/truncate.yml
      become: true
    - import_tasks: ../roles/before_bench/nginx.yml
      become: true
    - import_tasks: ../roles/before_bench/mysql.yml
      become: true
