---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: isucon
    # TODO: インスタンスに接続するための秘密鍵を指定する
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  hosts:
    # bench:
    #   ansible_host: 18.182.74.238
  children:
    isucon_server:
      hosts:
        # TODO: インスタンスのホスト名かIPアドレスを指定する
        isucon1:
          ansible_host: 13.114.86.171
          server_id: s1
        isucon2:
          ansible_host: 35.74.44.161
          server_id: s2
        isucon3:
          ansible_host: 54.95.241.68
          server_id: s3
