---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: isucon
    # TODO: インスタンスに接続するための秘密鍵を指定する
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  hosts:
    # bench:
    #   ansible_host: 18.182.74.238
  children:
    isucon_server:
      hosts:
        # TODO: インスタンスのホスト名かIPアドレスを指定する
        isucon1:
          ansible_host: 57.182.133.233
          server_id: s1
        isucon2:
          ansible_host: 18.181.50.22
          server_id: s2
        isucon3:
          ansible_host: 18.179.180.81
          server_id: s3
