---
- name: install alp
  get_url:
    url: https://github.com/tkuchiki/alp/releases/download/v1.0.21/alp_linux_amd64.tar.gz
    dest: /tmp
    mode: 0644

- name: extract alp
  unarchive:
    src: /tmp/alp_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755

- name: execute alp
  shell: alp --version
