---
- name: install slp
  get_url:
    url: https://github.com/tkuchiki/slp/releases/download/v0.2.1/slp_linux_amd64.tar.gz
    dest: /tmp
    mode: 0644

- name: extract slp
  unarchive:
    src: /tmp/slp_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755

- name: execute slp
  shell: slp
