---
- name: install slm
  get_url:
    url: https://github.com/furusax0621/slack-messenger-lite/releases/download/v0.0.6/sml_0.0.6_Linux_x86_64.tar.gz
    dest: /tmp
    mode: 0644

- name: extract slm
  unarchive:
    src: /tmp/sml_0.0.6_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
